### ISSUE TITLE
Forecast

### ISSUE THREAD

**Issue by davewatson91** [madpilot/hass-amber-electric#2]
The real-time pricing looks spot-on to me! 

Are there plans to bring the forecast in? (I currently run some quick calculations in NodeRed to calculate the cheapest x periods throughout the next 12 hours to run the heavy consumers.

**Comment by madpilot** [comment]
Yep! Just trying to work out the best way to do it.

There are two options:

1. A forecast sensor
2. Attributes on the current price (kind of like the old one)

2 is nice because there is no need to derive a default state value, but one is nice for keeping things clean.

It'll be a fast follow though.

**Comment by madpilot** [comment]
Done. I went with Option 1. The default state is the next forecast interval, and the rest are an attribute similar to how the old integration worked.

![image](https://user-images.githubusercontent.com/19585/122912634-df9e0980-d39b-11eb-904d-57db696d29a8.png)

**Comment by davewatson91** [comment]
@madpilot you're an absolute gun. Thanks so much! Can't believe how quick you've got this smashed out.
